### ISSUE TITLE
Feature Request: Multi-Monitor Support

### ISSUE THREAD

**Issue by ldsands** [51n7/kTile#1]
As the title says, it would be nice to have multiple monitor support. In my case I have two monitors that are different (one vertical). Setting up tiles for this case doesn't seem to be viable using kTile at the moment.

**Comment by 51n7** [comment]
Are you suggesting the new custom region is always specific to a selected monitor? Or do you mean having a way to quickly move the window between monitors?

Adding a new option here to specify the monitor might not be that bad:

![image](https://user-images.githubusercontent.com/2657818/211109905-4dffc7ed-fbd5-4ea0-a755-4dfb77a95950.png)

I'll have to source another monitor first though 😅

**Comment by ldsands** [comment]
> Are you suggesting the new custom region is always specific to a selected monitor? Or do you mean having a way to quickly move the window between monitors?
> 
> Adding a new option here to specify the monitor might not be that bad:
> 
> ![image](https://user-images.githubusercontent.com/2657818/211109905-4dffc7ed-fbd5-4ea0-a755-4dfb77a95950.png)
> 
> I'll have to source another monitor first though 😅

Probably both, FancyZones from PowerToys on windows is just about perfect for this it has an independent setting of the zones for each monitor but you can also move windows between zones across all monitors.

**Comment by i8degrees** [comment]
Hi,

I second the motion for supporting this feature. My expectation is for the configuration window (the main window of this script, I believe?) to appear on whichever display has either one of the following conditions set:

a) active window (in focus)
b) window that my mouse pointer is hovering above

Let us call option `a` the default.

Option `b` ought to allow for the correct expectation when users have customized their window manager to automatically focus the window their mouse cursor is under. (Years ago, I was one such user!)

It is a sad shame that I am so busy right now with other things, or else I would spend the few hours necessary to hack in support into your script myself and submit a pull request! :-( Perhaps I will revisit this topic at some point in the future.

Cheers,
Jeff

**Comment by 51n7** [comment]
Sorry it took me a long time to source a bare metal Linux box with a second display but I can now start looking into this feature.

Although having said that it looks like it's already working as expected according to @i8degrees description, at least for me in KDE (Neon) 5.27. I can focus a display and the main kTile window will then appear in **_that_** display, I can also select a window then mouse over to the second display and hit the shortcut for it's assigned position and it will appear on the correct display.

I got to say I'm really shocked this just works, I definitely didnt account for this when I originally build the script but if it's still not working as described above let me know what distro/version etc you're using and I'll see what I can do.

Given that focusing a second display works I'll take some time to look into the initial feature mentioned by @ldsands :

> "it has an independent setting of the zones for each monitor but you can also move windows between zones across all monitors"

**Comment by 51n7** [comment]
![Screenshot_20230726_205118](https://github.com/51n7/kTile/assets/2657818/3d74c50b-503c-4057-980b-217a51c4624d)

I've pushed a change for this feature but I havnt packaged it yet for the KDE store as it's a little experimental but feel free to pull the changes and check it out.

The main issue is that yes I can assign a window to a screen but I cant get any information about that screen to then resize the window to it's correct position on the new screen because of limitations in the [Kwin API](https://develop.kde.org/docs/plasma/kwin/api/). Basically as mentioned it just doesnt provide info for other screens, just the active screen :frowning_face:. Although you could just move your cursor over to the other screen so it becomes the new active screen and hit the shortcut again :thinking:. However if your screens are the same size then you wont notice a problem as the window wont need to adjust its size/position anyway.

As for moving a windows between zones across all monitors Kwin already has a shortcut for moving the window under "Window to Previous Screen" and "Window to Next Screen" and looks like it defaults to Meta+Shift+Left/Right. I was experimenting with double pressing the shortcut to move the window to the next screen but found it could be annoying when switching spaces quickly on one screen as it will cause a double press and move the window unnecessarily. It's something I will need to find a good UX solution for.

This feature will have to be a work-in-progress so I'll keep this issue open until I can find a solution for resizing the window after moving to the next screen but it might rely on an API change so dont hold your breath.

**Comment by i8degrees** [comment]
@51n7 heyya! I have checked out a local repository of your latest changes; in the middle of testing everything right now. I will do a proper reply here as soon as I am done with tests N all.

Just by reading through your code additions, it looks like you implemented exactly as I was thinking inside my head. Excited to see how it plays!

![Screenshot_20230729_174128](https://github.com/51n7/kTile/assets/1329364/3d170f26-3d0b-48ad-909e-512379833da7)

**Comment by 51n7** [comment]
While updating this script for Plasma 6 I was able to address the outstanding issue in this thread too, so now when you assign a window to a specific desktop it will move the window AND resize it correctly.

I'm ready to call this issue closed but I'll leave it open for a bit longer in case there are any further comments.
